version: '3'
services:
  kibana:
    image: kibana:7.10.1
    ports:
      - "80:5601"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    links:
      - kibana
  demo-site:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./demo-site:/usr/share/nginx/html:ro
  jef-monitor:
    image: openjdk:8u102-jdk
    ports:
      - "8099:8082"
    volumes:
      - ./norconex-jef-monitor:/home
      - ./data:/data
    working_dir: /home
    environment:
      - ROOT_DIR=/home
    command: java -Dlog4j.configuration="file:///home/classes/log4j.properties" -Dfile.encoding=UTF8 -cp "./lib/*:./classes" com.norconex.jefmon.server.JEFMonServer
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - "./data/docker/mysql:/var/lib/mysql"
      - "./docker/db/config:/etc/mysql/conf.d"
