version: '3'
services:
  kibana:
    image: kibana:7.10.1
    ports:
      - "80:5601"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"
    links:
      - kibana
  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    volumes:
      - "./data/docker/mysql:/var/lib/mysql"
      - "./docker/db/config:/etc/mysql/conf.d"
